### ISSUE TITLE
STL Files provided don't match with video

### ISSUE THREAD

**Issue by IamMistborn** [nickpetersen93/LIQ_HD#2]
Hey there, I was going through the tutorial when I realized the Youtube video STL files and the STL files provided on Thingiverse don't match up. What's more, it looks like the STL files have additional hardware that isn't mentioned in the video, Step-By-Step tutorial, or materials list. I'm mostly wondering if I'm missing something crucial that was added later on. Thanks!

**Comment by nickpetersen93** [comment]
Hello! We have not uploaded anything to Thingiverse, but it looks like there is a modified version that was adapted from our system made by another lab [(link)](https://www.thingiverse.com/thing:6301818). From what I can tell from their design, the general build of the electronic components in the same, but with a modified in-cage sipper sensor to fit their cages.
