### ISSUE TITLE
Minor Errors After Uploading The Code

### ISSUE THREAD

**Issue by EVienneau03** [nickpetersen93/LIQ_HD#4]
Hi there,

The lab i am apart of has decided to switch over to the LIQ HD to gain a more accurate drinking representation of our mice colony. We have also had a hanful of changes to the device top (resized to fir our cages, reinforced some areas and added clips so it does not sag) and leg height.

A few issue that have come up when trying to set up the LIQ HD

1. The SD card said SD Card failed..., I have tried a handful of different cards, not new but have been working and reformatted since their previous use. 

3. The other issue is changing the date and time. It did not sync to my computers date and time, but it has set the date to 72/96/2095 and the time to 72:00. When i try to change the date and time, the device will not accept my changes as i clear the time, enter the new number and confirm it with ok and it will disregard my changes that i attempted to make. Nor will it change when i hit save. All other changable setting are wokring perfectly fine!

If you have any advice on how to fix both the sd card issue and the date and time issue?

Best,
Evan V.
Emmanuel College, Crofton Lab Assistant

**Comment by nickpetersen93** [comment]
Hey Evan,

The most likely a hardware issue with the data logger shield, which also includes the real-time clock. Take a close look at the data logger - Is the "CS" solder pad connection cut? Was a jumper wire connected from pin 7 to the "CS" pin? Are any of the pins accidentally bridged together with solder? Were any PCB tracks (conductive paths used to connect each point on the board) damaged during the soldering process? If everything looks correct, the board itself may be faulty and you may want to try a different data logger.

Hope this helps! Feel free to reach out if you're still having problems.

Nick
